POST http://localhost:3001/employees/save
Content-Type: application/json

{
  "name"    : "Poly Stark",
  "email"   : "poly.stark@avengers.com",
  "username": "polystark",
  "role_id" : 1
}

### save: 404 same username
POST http://localhost:3001/employees/save
Content-Type: application/json

{
  "name"    : "Poly Stark",
  "email"   : "poly.stark@avengers.com",
  "username": "tonystark",
  "role_id" : 1
}

### save: 400 no role
POST http://localhost:3001/employees/save
Content-Type: application/json

{
  "name"    : "Poly Stark",
  "email"   : "poly.star2k@avengers.com",
  "username": "tonystark3"

}


### save: 404 same email

POST http://localhost:3001/employees/save
Content-Type: application/json

{
  "name"    : "Poly Stark",
  "email"   : "tony.stark@avengers.com",
  "username": "tonystarkother",
  "role_id" : 1
}


### roles save
POST http://localhost:3001/roles/save
Content-Type: application/json

{
  "role_code": "spiderman2",
  "role_name": "The Flyer One"
}



### user save:
POST http://localhost:3001/employees/save
Content-Type: application/json

{
  "role_code": "spiderman2",
  "role_name": "The Flyer One"
}
